// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {

	image: {
		repository: "quay.io/keycloak/keycloak"
		digest:     "sha256:8772ab5e763f3374b7bb70bce4a96ad384b39c548c40007113538e103ee8a8f2"
		tag:        "23.0.5"
	}

}
