name: Release and sign module
on:
    push:
        tags: ['*'] # semver format

permissions:
    contents: read # needed for checkout
    packages: write # needed for GHCR access
    id-token: write # needed for signing

jobs:
    push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Cosign
              uses: sigstore/cosign-installer@main
            - name: Setup Timoni
              uses: stefanprodan/timoni/actions/setup@main
            - name: Login to GHCR
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Vet module
              run: |
                  timoni mod vet . -f test/minimum-values.cue
            - name: Push and Sign
              run: |
                  timoni mod push . \
                    oci://ghcr.io/${{ github.repository_owner }}/keycloak \
                    --version ${{ github.ref_name }} \
                    --sign=cosign \
                    --latest  \
                    -a 'org.opencontainers.image.licenses=Apache-2.0' \
                    -a 'org.opencontainers.image.source=https://github.com/${{ github.repository }}' \
                    -a 'org.opencontainers.image.description=A Keycloak module.' \
